.TH Common Test Application 6 "common_test 1.30" "Ericsson AB" "Erlang Module Definition"
.SH NAME
Common Test Application \- A framework for automated testing of any target nodes
.SH DESCRIPTION
.PP
The \fICommon Test\fR framework is an environment for implementing and performing automatic and semi-automatic execution of test cases.

.PP
In brief, \fICommon Test\fR supports:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
Automated execution of test suites (sets of test cases)

.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
Logging of events during execution

.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
HTML presentation of test suite results

.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
HTML presentation of test suite code

.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
Support functions for test suite authors

.RE

.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
Step-by-step execution of test cases

.RE

