.TH Runtime tools Application 6 "runtime_tools 2.3.1" "Ericsson AB" "Erlang Module Definition"
.SH NAME
Runtime tools Application
.SH DESCRIPTION
.SS "Description"

.PP
This chapter describes the Runtime_Tools application in OTP, which provides low footprint tracing/debugging tools suitable for inclusion in a production system.

.SS "Configuration"

.PP
There are currently no configuration parameters available for this application.

.SS "SEE ALSO"

.PP
application(3)

