.TH eprof 3 "tools 4.1.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
eprof \- A Time Profiling Tool for Erlang

.SH DESCRIPTION
.PP
The module \fIeprof\fR provides a set of functions for time profiling of Erlang programs to find out how the execution time is used. The profiling is done using the Erlang trace BIFs. Tracing of local function calls for a specified set of processes is enabled when profiling is begun, and disabled when profiling is stopped.

.PP
When using Eprof, expect a slowdown in program execution.

.SH DATA TYPES
.LP
.B
\fBanalyze_type() :: procs | total.\fR

.br
.RS

.RE
.B
\fBtrace_pattern_mfa() :: {atom(), atom(), arity() | '_'}.\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBanalyze(TypeOpts) -> ok | nothing_to_analyze\fR
\fB                 when TypeOpts :: analyze_type().\fR

.br
.RS
.PP
If \fITypeOpts\fR is an atom, it is assumed to be a module name, and this call is equivalent to \fIanalyze(TypeOpts, [])\fR.

.PP
Otherwise, if \fITypeOpts\fR is a list, it assumed to be a list of options, and this call is equivalent to \fIanalyze(procs, TypeOpts)\fR.


.RE
.B
\fBanalyze(Type, Options) -> ok | nothing_to_analyze\fR
\fB                 when\fR
\fB                     Type :: analyze_type(),\fR
\fB                     Options :: [Option],\fR
\fB                     Option :: {filter, Filter} | {sort, Sort},\fR
\fB                     Filter ::\fR
\fB                         [{calls, non_neg_integer()} | {time, float()}],\fR
\fB                     Sort :: time | calls | mfa.\fR

.br
.RS
.PP
Call this function when profiling has been stopped to display the results.

.PP
If \fIType\fR is \fIprocs\fR, the time spent in each function is shown separately for each profiled process.

.PP
If \fIType\fR is \fItotal\fR, the time spent in each function is shown combined for each profiled process.

.PP
Time is shown as percentage of total time and as absolute time in micro seconds.


.RE
.B
\fBlog(File) -> ok when File :: atom() | file:filename().\fR

.br
.RS
.PP
Call this function to ensure that the results displayed by \fIanalyze/0,1,2\fR are printed to the file \fIFile\fR as well as to the screen.


.RE
.B
\fBprofile(Fun) -> {ok, Value} | {error, Reason}\fR
\fB                 when\fR
\fB                     Fun :: fun(() -> term()),\fR
\fB                     Value :: term(),\fR
\fB                     Reason :: term();\fR
\fB             (Rootset) -> profiling | {error, Reason}\fR
\fB                 when Rootset :: [atom() | pid()], Reason :: term().\fR

.br
.RS
.PP
If \fIFunRootset\fR is a fun, this call is equivalent to \fIprofile([], FunRootset)\fR.

.PP
If \fIFunRootset\fR is a list, it is assumed to be a \fIRootset\fR, and this call is equivalent to \fIstart_profiling(Rootset)\fR.


.RE
.B
\fBprofile(Fun, Options) -> {ok, Value} | {error, Reason}\fR
\fB                 when\fR
\fB                     Fun :: fun(() -> term()),\fR
\fB                     Options ::\fR
\fB                         [set_on_spawn | {set_on_spawn, boolean()}],\fR
\fB                     Value :: term(),\fR
\fB                     Reason :: term();\fR
\fB             (Rootset, Fun) -> {ok, Value} | {error, Reason}\fR
\fB                 when\fR
\fB                     Rootset :: [atom() | pid()],\fR
\fB                     Fun :: fun(() -> term()),\fR
\fB                     Value :: term(),\fR
\fB                     Reason :: term().\fR

.br
.RS
.PP
If \fIArg1\fR is a fun and \fIArg2\fR is list, this call is equivalent to \fIprofile([], Arg1, {'_','_','_'}, Arg2)\fR.

.PP
If \fIArg1\fR is a list and \fIArg2\fR is a fun, this call is equivalent to \fIprofile(Arg1, Arg2, {'_','_','_'}, Arg1)\fR.


.RE
.B
\fBprofile(Rootset, Module, Function, Args) ->\fR
\fB                 {ok, Value} | {error, Reason}\fR
\fB                 when\fR
\fB                     Rootset :: [atom() | pid()],\fR
\fB                     Module :: module(),\fR
\fB                     Function :: atom(),\fR
\fB                     Args :: [term()],\fR
\fB                     Value :: term(),\fR
\fB                     Reason :: term();\fR
\fB             (Rootset, Fun, Pattern, Options) ->\fR
\fB                 {ok, Value} | {error, Reason}\fR
\fB                 when\fR
\fB                     Rootset :: [atom() | pid()],\fR
\fB                     Fun :: fun(() -> term()),\fR
\fB                     Pattern :: trace_pattern_mfa(),\fR
\fB                     Options ::\fR
\fB                         [set_on_spawn | {set_on_spawn, boolean()}],\fR
\fB                     Value :: term(),\fR
\fB                     Reason :: term().\fR

.br
.RS
.PP
This function spawns a process that applies a fun or an an function, and then starts profiling for the spawned proceses as well as the processes in \fIRootset\fR (and any new processes spawned from them).

.PP
If \fIArg1\fR is a fun, \fIArg2\fR is expected to be a trace pattern, and \fIArg3\fR a list of options. In that case, this call is equivalent to:

.PP
\fIprofile(Rootset, erlang, apply, [Arg1, []], Arg2, Arg3)\fR

.PP
If \fIArg1\fR is an atom, \fIArg1\fR is assumed to be a module name, \fIArg2\fR the name of the function in that module, and \fIArg3\fR a list of arguments to be used when calling that function. In that case, this call is equivalent to:

.PP
\fIprofile(Rootset, Arg1, Arg2, Arg3, {'_','_','_'}, [{set_on_spawn, true}])\fR


.RE
.B
\fBprofile(Rootset, Module, Function, Args, Pattern, Options) ->\fR
\fB                 {ok, Value} | {error, Reason}\fR
\fB                 when\fR
\fB                     Rootset :: [atom() | pid()],\fR
\fB                     Module :: module(),\fR
\fB                     Function :: atom(),\fR
\fB                     Args :: [term()],\fR
\fB                     Pattern :: trace_pattern_mfa(),\fR
\fB                     Options ::\fR
\fB                         [set_on_spawn | {set_on_spawn, boolean()}],\fR
\fB                     Value :: term(),\fR
\fB                     Reason :: term().\fR

.br
.RS
.PP
This function spawns a process \fIP\fR that \fIapply(Module, Function, Args)\fR, and then starts profiling for \fIP\fR and the processes in \fIRootset\fR (and any new processes spawned from them).

.PP
\fIRootset\fR is a list of pids and registered names.

.PP
Information about activity in any profiled process is stored in the Eprof database.

.PP
If tracing could be enabled for \fIP\fR and all processes in \fIRootset\fR, the function returns \fI{ok,Value}\fR when \fIFun()\fR/\fIapply\fR returns with the value \fIValue\fR, or \fI{error,Reason}\fR if \fIFun()\fR/\fIapply\fR fails with exit reason \fIReason\fR. Otherwise it returns \fI{error, Reason}\fR immediately.

.PP
The \fIset_on_spawn\fR option will active call time tracing for all processes spawned by processes in the rootset. This is the default behaviour.

.PP
The programmer must ensure that the function given as argument is truly synchronous and that no work continues after the function has returned a value.


.RE
.B
\fBstart() -> {ok, Pid} | {error, Reason}\fR
\fB               when Pid :: pid(), Reason :: {already_started, Pid}.\fR

.br
.RS
.PP
Starts the Eprof server which holds the internal state of the collected data.


.RE
.B
\fBstart_profiling(Rootset, Pattern, Options) ->\fR
\fB                         profiling | {error, Reason}\fR
\fB                         when\fR
\fB                             Rootset :: [atom() | pid()],\fR
\fB                             Pattern :: trace_pattern_mfa(),\fR
\fB                             Options ::\fR
\fB                                 [set_on_spawn |\fR
\fB                                  {set_on_spawn, boolean()}],\fR
\fB                             Reason :: term().\fR

.br
.RS
.PP
Starts profiling for the processes in \fIRootset\fR (and any new processes spawned from them).

.PP
Information about activity in any profiled process is stored in the Eprof database.

.PP
\fIRootset\fR is a list of pids and registered names.

.PP
The function returns \fIprofiling\fR if tracing could be enabled for all processes in \fIRootset\fR, or \fIerror\fR otherwise.

.PP
A pattern can be selected to narrow the profiling. For instance a specific module can be selected, and only the code executed in that module will be profiled.

.PP
The \fIset_on_spawn\fR option will active call time tracing for all processes spawned by processes in the rootset. This is the default behaviour.


.RE
.B
\fBstop() -> stopped.\fR

.br
.RS
.PP
Stops the Eprof server.


.RE
.B
\fBstop_profiling() -> profiling_stopped | profiling_already_stopped.\fR

.br
.RS
.PP
Stops profiling started with \fIstart_profiling/1\fR or \fIprofile/1\fR.


.RE
