.TH wxAcceleratorEntry 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxAcceleratorEntry \- An object used by an application wishing to create an accelerator table (see \fIwxAcceleratorTable\fR).

.SH DESCRIPTION
.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxAcceleratorTable\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxWindow:setAcceleratorTable/2\fR

.RE

.PP
wxWidgets docs: wxAcceleratorEntry

.SH DATA TYPES
.LP
.B
\fBwxAcceleratorEntry() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBdestroy(This :: wxAcceleratorEntry()) -> ok.\fR

.br
.RS
.PP
Destroys the object


.RE
.B
\fBgetCommand(This) -> integer() when This :: wxAcceleratorEntry().\fR

.br
.RS
.PP
Returns the command identifier for the accelerator table entry.


.RE
.B
\fBgetFlags(This) -> integer() when This :: wxAcceleratorEntry().\fR

.br
.RS
.PP
Returns the flags for the accelerator table entry.


.RE
.B
\fBgetKeyCode(This) -> integer() when This :: wxAcceleratorEntry().\fR

.br
.RS
.PP
Returns the keycode for the accelerator table entry.


.RE
.B
\fBnew([Option]) -> wxAcceleratorEntry()\fR
\fB             when\fR
\fB                 Option ::\fR
\fB                     {flags, integer()} |\fR
\fB                     {keyCode, integer()} |\fR
\fB                     {cmd, integer()} |\fR
\fB                     {item, wxMenuItem:wxMenuItem()};\fR
\fB         (Entry) -> wxAcceleratorEntry()\fR
\fB             when Entry :: wxAcceleratorEntry().\fR

.br
.RS
.PP
Copy ctor.


.RE
.B
\fBset(This, Flags, KeyCode, Cmd, [Option]) -> ok\fR
\fB             when\fR
\fB                 This :: wxAcceleratorEntry(),\fR
\fB                 Flags :: integer(),\fR
\fB                 KeyCode :: integer(),\fR
\fB                 Cmd :: integer(),\fR
\fB                 Option :: {item, wxMenuItem:wxMenuItem()}.\fR

.br
.RS
.PP
Sets the accelerator entry parameters.


.RE
