.TH wxBitmapButton 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxBitmapButton \- A bitmap button is a control that contains a bitmap.

.SH DESCRIPTION
.PP
Notice that since wxWidgets 2.9.1 bitmap display is supported by the base \fIwxButton\fR class itself and the only tiny advantage of using this class is that it allows specifying the bitmap in its constructor, unlike \fIwxButton\fR. Please see the base class documentation for more information about images support in \fIwxButton\fR.

.SS "Styles"

.PP
This class supports the following styles:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
wxBU_LEFT: Left-justifies the bitmap label.

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
wxBU_TOP: Aligns the bitmap label to the top of the button.

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
wxBU_RIGHT: Right-justifies the bitmap label.

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
wxBU_BOTTOM: Aligns the bitmap label to the bottom of the button. Note that the wxBU_EXACTFIT style supported by \fIwxButton\fR is not used by this class as bitmap buttons don't have any minimal standard size by default.

.RE

.PP
See: \fIwxButton\fR

.PP
This class is derived, and can use functions, from:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxButton\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxControl\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxWindow\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxEvtHandler\fR

.RE

.PP
wxWidgets docs: wxBitmapButton

.SS "Events"

.PP
Event types emitted from this class:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIcommand_button_clicked\fR

.RE

.SH DATA TYPES
.LP
.B
\fBwxBitmapButton() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBcreate(This, Parent, Id, Bitmap, [Option]) -> boolean()\fR
\fB                when\fR
\fB                    This :: wxBitmapButton(),\fR
\fB                    Parent :: wxWindow:wxWindow(),\fR
\fB                    Id :: integer(),\fR
\fB                    Bitmap :: wxBitmap:wxBitmap(),\fR
\fB                    Option ::\fR
\fB                        {pos, {X :: integer(), Y :: integer()}} |\fR
\fB                        {size, {W :: integer(), H :: integer()}} |\fR
\fB                        {style, integer()} |\fR
\fB                        {validator, wx:wx_object()}.\fR

.br
.RS
.PP
Button creation function for two-step creation.

.PP
For more details, see \fInew/4\fR.


.RE
.B
\fBdestroy(This :: wxBitmapButton()) -> ok.\fR

.br
.RS
.PP
Destroys the object


.RE
.B
\fBnew() -> wxBitmapButton().\fR

.br
.RS
.PP
Default ctor.


.RE
.B
\fBnew(Parent, Id, Bitmap, [Option]) -> wxBitmapButton()\fR
\fB             when\fR
\fB                 Parent :: wxWindow:wxWindow(),\fR
\fB                 Id :: integer(),\fR
\fB                 Bitmap :: wxBitmap:wxBitmap(),\fR
\fB                 Option ::\fR
\fB                     {pos, {X :: integer(), Y :: integer()}} |\fR
\fB                     {size, {W :: integer(), H :: integer()}} |\fR
\fB                     {style, integer()} |\fR
\fB                     {validator, wx:wx_object()}.\fR

.br
.RS
.PP
Constructor, creating and showing a button.

.PP
Remark: The bitmap parameter is normally the only bitmap you need to provide, and wxWidgets will draw the button correctly in its different states. If you want more control, call any of the functions \fISetBitmapPressed()\fR (not implemented in wx), \fIwxButton:setBitmapFocus/2\fR, \fIwxButton:setBitmapDisabled/2\fR.

.PP
See: \fIcreate/5\fR


.RE
.B
\fBnewCloseButton(Parent, Winid) -> wxBitmapButton()\fR
\fB                        when\fR
\fB                            Parent :: wxWindow:wxWindow(),\fR
\fB                            Winid :: integer().\fR

.br
.RS
.PP
Helper function creating a standard-looking "Close" button.

.PP
To get the best results, platform-specific code may need to be used to create a small, title bar-like "Close" button. This function is provided to avoid the need to test for the current platform and creates the button with as native look as possible.

.PP
Return: The new button.

.PP
Since: 2.9.5


.RE
