.TH wxBufferedDC 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxBufferedDC \- This class provides a simple way to avoid flicker: when drawing on it, everything is in fact first drawn on an in-memory buffer (a \fIwxBitmap\fR) and then copied to the screen, using the associated \fIwxDC\fR, only once, when this object is destroyed.

.SH DESCRIPTION
.PP
\fIwxBufferedDC\fR itself is typically associated with \fIwxClientDC\fR, if you want to use it in your \fIEVT_PAINT\fR handler, you should look at \fIwxBufferedPaintDC\fR instead.

.PP
When used like this, a valid \fIDC\fR must be specified in the constructor while the \fIbuffer\fR bitmap doesn't have to be explicitly provided, by default this class will allocate the bitmap of required size itself. However using a dedicated bitmap can speed up the redrawing process by eliminating the repeated creation and destruction of a possibly big bitmap. Otherwise, \fIwxBufferedDC\fR can be used in the same way as any other device context.

.PP
Another possible use for \fIwxBufferedDC\fR is to use it to maintain a backing store for the window contents. In this case, the associated \fIDC\fR may be NULL but a valid backing store bitmap should be specified.

.PP
Finally, please note that GTK+ 2.0 as well as macOS provide double buffering themselves natively. You can either use \fIwxWindow:isDoubleBuffered/1\fR to determine whether you need to use buffering or not, or use \fIwxAutoBufferedPaintDC\fR (not implemented in wx) to avoid needless double buffering on the systems which already do it automatically.

.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxDC\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxMemoryDC\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxBufferedPaintDC\fR

.RE

.PP
This class is derived, and can use functions, from:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxMemoryDC\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxDC\fR

.RE

.PP
wxWidgets docs: wxBufferedDC

.SH DATA TYPES
.LP
.B
\fBwxBufferedDC() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBdestroy(This :: wxBufferedDC()) -> ok.\fR

.br
.RS
.PP
Destroys the object


.RE
.B
\fBinit(This, Dc, Area) -> ok\fR
\fB              when\fR
\fB                  This :: wxBufferedDC(),\fR
\fB                  Dc :: wxDC:wxDC(),\fR
\fB                  Area :: {W :: integer(), H :: integer()};\fR
\fB          (This, Dc, [Option]) -> ok\fR
\fB              when\fR
\fB                  This :: wxBufferedDC(),\fR
\fB                  Dc :: wxDC:wxDC(),\fR
\fB                  Option ::\fR
\fB                      {buffer, wxBitmap:wxBitmap()} | {style, integer()}.\fR

.br
.RS

.RE
.B
\fBinit(This, Dc, Area, [Option]) -> ok\fR
\fB              when\fR
\fB                  This :: wxBufferedDC(),\fR
\fB                  Dc :: wxDC:wxDC(),\fR
\fB                  Area :: {W :: integer(), H :: integer()},\fR
\fB                  Option :: {style, integer()}.\fR

.br
.RS
.PP
Initializes the object created using the default constructor.

.PP
Please see the constructors for parameter details.


.RE
.B
\fBnew() -> wxBufferedDC().\fR

.br
.RS
.PP
Default constructor.

.PP
You must call one of the \fIinit/4\fR methods later in order to use the device context.


.RE
.B
\fBnew(Dc, Area) -> wxBufferedDC()\fR
\fB             when\fR
\fB                 Dc :: wxDC:wxDC(),\fR
\fB                 Area :: {W :: integer(), H :: integer()};\fR
\fB         (Dc, [Option]) -> wxBufferedDC()\fR
\fB             when\fR
\fB                 Dc :: wxDC:wxDC(),\fR
\fB                 Option ::\fR
\fB                     {buffer, wxBitmap:wxBitmap()} | {style, integer()}.\fR

.br
.RS
.PP
Creates a buffer for the provided dc.

.PP
\fIinit/4\fR must not be called when using this constructor.


.RE
.B
\fBnew(Dc, Area, [Option]) -> wxBufferedDC()\fR
\fB             when\fR
\fB                 Dc :: wxDC:wxDC(),\fR
\fB                 Area :: {W :: integer(), H :: integer()},\fR
\fB                 Option :: {style, integer()}.\fR

.br
.RS
.PP
Creates a buffer for the provided \fIdc\fR.

.PP
\fIinit/4\fR must not be called when using this constructor.


.RE
