.TH wxGraphicsFont 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxGraphicsFont \- A \fIwxGraphicsFont\fR is a native representation of a font.

.SH DESCRIPTION
.PP
The contents are specific and private to the respective renderer. Instances are ref counted and can therefore be assigned as usual. The only way to get a valid instance is via \fIwxGraphicsContext:createFont/4\fR or \fIwxGraphicsRenderer:createFont/4\fR.

.PP
This class is derived, and can use functions, from:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGraphicsObject\fR

.RE

.PP
wxWidgets docs: wxGraphicsFont

.SH DATA TYPES
.LP
.B
\fBwxGraphicsFont() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
