.TH wxGridCellStringRenderer 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxGridCellStringRenderer \- This class may be used to format string data in a cell; it is the default for string cells.

.SH DESCRIPTION
.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellRenderer\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellBoolRenderer\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellFloatRenderer\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellNumberRenderer\fR

.RE

.PP
This class is derived, and can use functions, from:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellRenderer\fR

.RE

.PP
wxWidgets docs: wxGridCellStringRenderer

.SH DATA TYPES
.LP
.B
\fBwxGridCellStringRenderer() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBdestroy(This :: wxGridCellStringRenderer()) -> ok.\fR

.br
.RS
.PP
Destroys the object


.RE
.B
\fBnew() -> wxGridCellStringRenderer().\fR

.br
.RS

.RE
