.TH wxGridCellBoolRenderer 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxGridCellBoolRenderer \- This class may be used to format boolean data in a cell.

.SH DESCRIPTION
.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellRenderer\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellFloatRenderer\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellNumberRenderer\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellStringRenderer\fR

.RE

.PP
This class is derived, and can use functions, from:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxGridCellRenderer\fR

.RE

.PP
wxWidgets docs: wxGridCellBoolRenderer

.SH DATA TYPES
.LP
.B
\fBwxGridCellBoolRenderer() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBdestroy(This :: wxGridCellBoolRenderer()) -> ok.\fR

.br
.RS
.PP
Destroys the object


.RE
.B
\fBnew() -> wxGridCellBoolRenderer().\fR

.br
.RS

.RE
