.TH wxLogNull 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxLogNull \- This class allows you to temporarily suspend logging.

.SH DESCRIPTION
.PP
All calls to the log functions during the life time of an object of this class are just ignored.

.PP
In particular, it can be used to suppress the log messages given by wxWidgets itself but it should be noted that it is rarely the best way to cope with this problem as \fIall\fR log messages are suppressed, even if they indicate a completely different error than the one the programmer wanted to suppress.

.PP
For instance, the example of the overview:

.PP
would be better written as:

.PP
wxWidgets docs: wxLogNull

.SH DATA TYPES
.LP
.B
\fBwxLogNull() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBdestroy(This :: wxLogNull()) -> ok.\fR

.br
.RS
.PP
Destroys the object


.RE
.B
\fBnew() -> wxLogNull().\fR

.br
.RS
.PP
Suspends logging.


.RE
