.TH wxPageSetupDialogData 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxPageSetupDialogData \- This class holds a variety of information related to \fIwxPageSetupDialog\fR.

.SH DESCRIPTION
.PP
It contains a \fIwxPrintData\fR member which is used to hold basic printer configuration data (as opposed to the user-interface configuration settings stored by \fIwxPageSetupDialogData\fR).

.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
Overview printing

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxPageSetupDialog\fR

.RE

.PP
wxWidgets docs: wxPageSetupDialogData

.SH DATA TYPES
.LP
.B
\fBwxPageSetupDialogData() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBdestroy(This :: wxPageSetupDialogData()) -> ok.\fR

.br
.RS
.PP
Destroys the object


.RE
.B
\fBenableHelp(This, Flag) -> ok\fR
\fB                    when\fR
\fB                        This :: wxPageSetupDialogData(),\fR
\fB                        Flag :: boolean().\fR

.br
.RS
.PP
Enables or disables the "Help" button (Windows only).


.RE
.B
\fBenableMargins(This, Flag) -> ok\fR
\fB                       when\fR
\fB                           This :: wxPageSetupDialogData(),\fR
\fB                           Flag :: boolean().\fR

.br
.RS
.PP
Enables or disables the margin controls (Windows only).


.RE
.B
\fBenableOrientation(This, Flag) -> ok\fR
\fB                           when\fR
\fB                               This :: wxPageSetupDialogData(),\fR
\fB                               Flag :: boolean().\fR

.br
.RS
.PP
Enables or disables the orientation control (Windows only).


.RE
.B
\fBenablePaper(This, Flag) -> ok\fR
\fB                     when\fR
\fB                         This :: wxPageSetupDialogData(),\fR
\fB                         Flag :: boolean().\fR

.br
.RS
.PP
Enables or disables the paper size control (Windows only).


.RE
.B
\fBenablePrinter(This, Flag) -> ok\fR
\fB                       when\fR
\fB                           This :: wxPageSetupDialogData(),\fR
\fB                           Flag :: boolean().\fR

.br
.RS
.PP
Enables or disables the "Printer" button, which invokes a printer setup dialog.


.RE
.B
\fBgetDefaultInfo(This) -> boolean()\fR
\fB                        when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns true if the dialog will simply return default printer information (such as orientation) instead of showing a dialog (Windows only).


.RE
.B
\fBgetDefaultMinMargins(This) -> boolean()\fR
\fB                              when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns true if the page setup dialog will take its minimum margin values from the currently selected printer properties (Windows only).


.RE
.B
\fBgetEnableHelp(This) -> boolean()\fR
\fB                       when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns true if the printer setup button is enabled.


.RE
.B
\fBgetEnableMargins(This) -> boolean()\fR
\fB                          when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns true if the margin controls are enabled (Windows only).


.RE
.B
\fBgetEnableOrientation(This) -> boolean()\fR
\fB                              when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns true if the orientation control is enabled (Windows only).


.RE
.B
\fBgetEnablePaper(This) -> boolean()\fR
\fB                        when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns true if the paper size control is enabled (Windows only).


.RE
.B
\fBgetEnablePrinter(This) -> boolean()\fR
\fB                          when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns true if the printer setup button is enabled.


.RE
.B
\fBgetMarginBottomRight(This) -> {X :: integer(), Y :: integer()}\fR
\fB                              when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns the right (x) and bottom (y) margins in millimetres.


.RE
.B
\fBgetMarginTopLeft(This) -> {X :: integer(), Y :: integer()}\fR
\fB                          when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns the left (x) and top (y) margins in millimetres.


.RE
.B
\fBgetMinMarginBottomRight(This) -> {X :: integer(), Y :: integer()}\fR
\fB                                 when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns the right (x) and bottom (y) minimum margins the user can enter (Windows only).

.PP
Units are in millimetres.


.RE
.B
\fBgetMinMarginTopLeft(This) -> {X :: integer(), Y :: integer()}\fR
\fB                             when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns the left (x) and top (y) minimum margins the user can enter (Windows only).

.PP
Units are in millimetres.


.RE
.B
\fBgetPaperId(This) -> wx:wx_enum()\fR
\fB                    when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns the paper id (stored in the internal \fIwxPrintData\fR object).

.PP
See: \fIwxPrintData:setPaperId/2\fR


.RE
.B
\fBgetPaperSize(This) -> {W :: integer(), H :: integer()}\fR
\fB                      when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns the paper size in millimetres.


.RE
.B
\fBgetPrintData(This) -> wxPrintData:wxPrintData()\fR
\fB                      when This :: wxPageSetupDialogData().\fR

.br
.RS

.RE
.B
\fBisOk(This) -> boolean() when This :: wxPageSetupDialogData().\fR

.br
.RS
.PP
Returns true if the print data associated with the dialog data is valid.

.PP
This can return false on Windows if the current printer is not set, for example. On all other platforms, it returns true.


.RE
.B
\fBnew() -> wxPageSetupDialogData().\fR

.br
.RS
.PP
Default constructor.


.RE
.B
\fBnew(PrintData) -> wxPageSetupDialogData()\fR
\fB             when\fR
\fB                 PrintData ::\fR
\fB                     wxPrintData:wxPrintData() |\fR
\fB                     wxPageSetupDialogData:wxPageSetupDialogData().\fR

.br
.RS
.PP
Construct an object from a print data object.


.RE
.B
\fBsetDefaultInfo(This, Flag) -> ok\fR
\fB                        when\fR
\fB                            This :: wxPageSetupDialogData(),\fR
\fB                            Flag :: boolean().\fR

.br
.RS
.PP
Pass true if the dialog will simply return default printer information (such as orientation) instead of showing a dialog (Windows only).


.RE
.B
\fBsetDefaultMinMargins(This, Flag) -> ok\fR
\fB                              when\fR
\fB                                  This :: wxPageSetupDialogData(),\fR
\fB                                  Flag :: boolean().\fR

.br
.RS
.PP
Pass true if the page setup dialog will take its minimum margin values from the currently selected printer properties (Windows only).

.PP
Units are in millimetres.


.RE
.B
\fBsetMarginBottomRight(This, Pt) -> ok\fR
\fB                              when\fR
\fB                                  This :: wxPageSetupDialogData(),\fR
\fB                                  Pt :: {X :: integer(), Y :: integer()}.\fR

.br
.RS
.PP
Sets the right (x) and bottom (y) margins in millimetres.


.RE
.B
\fBsetMarginTopLeft(This, Pt) -> ok\fR
\fB                          when\fR
\fB                              This :: wxPageSetupDialogData(),\fR
\fB                              Pt :: {X :: integer(), Y :: integer()}.\fR

.br
.RS
.PP
Sets the left (x) and top (y) margins in millimetres.


.RE
.B
\fBsetMinMarginBottomRight(This, Pt) -> ok\fR
\fB                                 when\fR
\fB                                     This :: wxPageSetupDialogData(),\fR
\fB                                     Pt ::\fR
\fB                                         {X :: integer(),\fR
\fB                                          Y :: integer()}.\fR

.br
.RS
.PP
Sets the right (x) and bottom (y) minimum margins the user can enter (Windows only).

.PP
Units are in millimetres.


.RE
.B
\fBsetMinMarginTopLeft(This, Pt) -> ok\fR
\fB                             when\fR
\fB                                 This :: wxPageSetupDialogData(),\fR
\fB                                 Pt :: {X :: integer(), Y :: integer()}.\fR

.br
.RS
.PP
Sets the left (x) and top (y) minimum margins the user can enter (Windows only).

.PP
Units are in millimetres.


.RE
.B
\fBsetPaperId(This, Id) -> ok\fR
\fB                    when\fR
\fB                        This :: wxPageSetupDialogData(),\fR
\fB                        Id :: wx:wx_enum().\fR

.br
.RS
.PP
Sets the paper size id.

.PP
Calling this function overrides the explicit paper dimensions passed in \fIsetPaperSize/2\fR.

.PP
See: \fIwxPrintData:setPaperId/2\fR


.RE
.B
\fBsetPaperSize(This, Size) -> ok\fR
\fB                      when\fR
\fB                          This :: wxPageSetupDialogData(),\fR
\fB                          Size :: {W :: integer(), H :: integer()}.\fR

.br
.RS
.PP
Sets the paper size in millimetres.

.PP
If a corresponding paper id is found, it will be set in the internal \fIwxPrintData\fR object, otherwise the paper size overrides the paper id.


.RE
.B
\fBsetPrintData(This, PrintData) -> ok\fR
\fB                      when\fR
\fB                          This :: wxPageSetupDialogData(),\fR
\fB                          PrintData :: wxPrintData:wxPrintData().\fR

.br
.RS
.PP
Sets the print data associated with this object.


.RE
