.TH wxSizer 3 "wx 2.5.4" "Ericsson AB" "Erlang Module Definition"
.SH NAME
wxSizer \- \fIwxSizer\fR is the abstract base class used for laying out subwindows in a window.

.SH DESCRIPTION
.PP
You cannot use \fIwxSizer\fR directly; instead, you will have to use one of the sizer classes derived from it. Currently there are \fIwxBoxSizer\fR, \fIwxStaticBoxSizer\fR, \fIwxGridSizer\fR, \fIwxFlexGridSizer\fR, \fIwxWrapSizer\fR (not implemented in wx) and \fIwxGridBagSizer\fR.

.PP
The layout algorithm used by sizers in wxWidgets is closely related to layout in other GUI toolkits, such as Java's AWT, the GTK toolkit or the Qt toolkit. It is based upon the idea of the individual subwindows reporting their minimal required size and their ability to get stretched if the size of the parent window has changed.

.PP
This will most often mean that the programmer does not set the original size of a dialog in the beginning, rather the dialog will be assigned a sizer and this sizer will be queried about the recommended size. The sizer in turn will query its children, which can be normal windows, empty space or other sizers, so that a hierarchy of sizers can be constructed. Note that \fIwxSizer\fR does not derive from \fIwxWindow\fR and thus does not interfere with tab ordering and requires very little resources compared to a real window on screen.

.PP
What makes sizers so well fitted for use in wxWidgets is the fact that every control reports its own minimal size and the algorithm can handle differences in font sizes or different window (dialog item) sizes on different platforms without problems. If e.g. the standard font as well as the overall design of Motif widgets requires more space than on Windows, the initial dialog size will automatically be bigger on Motif than on Windows.

.PP
Sizers may also be used to control the layout of custom drawn items on the window. The \fIadd/4\fR, \fIinsert/5\fR, and \fIprepend/4\fR functions return a pointer to the newly added \fIwxSizerItem\fR. Just add empty space of the desired size and attributes, and then use the \fIwxSizerItem:getRect/1\fR method to determine where the drawing operations should take place.

.PP
Please notice that sizers, like child windows, are owned by the library and will be deleted by it which implies that they must be allocated on the heap. However if you create a sizer and do not add it to another sizer or window, the library wouldn't be able to delete such an orphan sizer and in this, and only this, case it should be deleted explicitly.

.PP
wxSizer flags

.PP
The "flag" argument accepted by \fIwxSizerItem\fR constructors and other functions, e.g. \fIadd/4\fR, is an OR-combination of the following flags. Two main behaviours are defined using these flags. One is the border around a window: the border parameter determines the border width whereas the flags given here determine which side(s) of the item that the border will be added. The other flags determine how the sizer item behaves when the space allotted to the sizer changes, and is somewhat dependent on the specific kind of sizer used.

.PP
See: Overview sizer

.PP
wxWidgets docs: wxSizer

.SH DATA TYPES
.LP
.B
\fBwxSizer() :: wx:wx_object().\fR

.br
.RS

.RE
.SH FUNCTIONS
.LP
.B
\fBadd(This, Width, Height) -> wxSizerItem:wxSizerItem()\fR
\fB             when\fR
\fB                 This :: wxSizer(),\fR
\fB                 Width :: integer(),\fR
\fB                 Height :: integer();\fR
\fB         (This, Window, Flags) -> wxSizerItem:wxSizerItem()\fR
\fB             when\fR
\fB                 This :: wxSizer(),\fR
\fB                 Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                 Flags :: wxSizerFlags:wxSizerFlags();\fR
\fB         (This, Window, [Option]) -> wxSizerItem:wxSizerItem()\fR
\fB             when\fR
\fB                 This :: wxSizer(),\fR
\fB                 Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                 Option ::\fR
\fB                     {proportion, integer()} |\fR
\fB                     {flag, integer()} |\fR
\fB                     {border, integer()} |\fR
\fB                     {userData, wx:wx_object()}.\fR

.br
.RS
.PP
Appends a child to the sizer.

.PP
\fIwxSizer\fR itself is an abstract class, but the parameters are equivalent in the derived classes that you will instantiate to use it so they are described here:


.RE
.B
\fBadd(This, Width, Height, [Option]) -> wxSizerItem:wxSizerItem()\fR
\fB             when\fR
\fB                 This :: wxSizer(),\fR
\fB                 Width :: integer(),\fR
\fB                 Height :: integer(),\fR
\fB                 Option ::\fR
\fB                     {proportion, integer()} |\fR
\fB                     {flag, integer()} |\fR
\fB                     {border, integer()} |\fR
\fB                     {userData, wx:wx_object()};\fR
\fB         (This, Width, Height, Flags) -> wxSizerItem:wxSizerItem()\fR
\fB             when\fR
\fB                 This :: wxSizer(),\fR
\fB                 Width :: integer(),\fR
\fB                 Height :: integer(),\fR
\fB                 Flags :: wxSizerFlags:wxSizerFlags().\fR

.br
.RS
.PP
Appends a spacer child to the sizer.


.RE
.B
\fBaddSpacer(This, Size) -> wxSizerItem:wxSizerItem()\fR
\fB                   when This :: wxSizer(), Size :: integer().\fR

.br
.RS
.PP
This base function adds non-stretchable space to both the horizontal and vertical orientation of the sizer.

.PP
More readable way of calling:

.PP
See: \fIaddSpacer/2\fR


.RE
.B
\fBaddStretchSpacer(This, [Option]) -> wxSizerItem:wxSizerItem()\fR
\fB                          when\fR
\fB                              This :: wxSizer(),\fR
\fB                              Option :: {prop, integer()}.\fR

.br
.RS
.PP
Adds stretchable space to the sizer.

.PP
More readable way of calling:


.RE
.B
\fBcalcMin(This) -> {W :: integer(), H :: integer()}\fR
\fB                 when This :: wxSizer().\fR

.br
.RS
.PP
This method is abstract and has to be overwritten by any derived class.

.PP
Here, the sizer will do the actual calculation of its children's minimal sizes.


.RE
.B
\fBclear(This, [Option]) -> ok\fR
\fB               when\fR
\fB                   This :: wxSizer(),\fR
\fB                   Option :: {delete_windows, boolean()}.\fR

.br
.RS
.PP
Detaches all children from the sizer.

.PP
If \fIdelete_windows\fR is true then child windows will also be deleted.

.PP
Notice that child sizers are always deleted, as a general consequence of the principle that sizers own their sizer children, but don't own their window children (because they are already owned by their parent windows).


.RE
.B
\fBdetach(This, Window) -> boolean()\fR
\fB                when\fR
\fB                    This :: wxSizer(),\fR
\fB                    Window :: wxWindow:wxWindow() | wxSizer:wxSizer();\fR
\fB            (This, Index) -> boolean()\fR
\fB                when This :: wxSizer(), Index :: integer().\fR

.br
.RS
.PP
Detach a item at position \fIindex\fR from the sizer without destroying it.

.PP
This method does not cause any layout or resizing to take place, call \fIlayout/1\fR to update the layout "on screen" after detaching a child from the sizer. Returns true if the child item was found and detached, false otherwise.

.PP
See: \fIremove/2\fR


.RE
.B
\fBfit(This, Window) -> {W :: integer(), H :: integer()}\fR
\fB             when This :: wxSizer(), Window :: wxWindow:wxWindow().\fR

.br
.RS
.PP
Tell the sizer to resize the \fIwindow\fR so that its client area matches the sizer's minimal size (\fIComputeFittingClientSize()\fR (not implemented in wx) is called to determine it).

.PP
This is commonly done in the constructor of the window itself, see sample in the description of \fIwxBoxSizer\fR.

.PP
Return: The new window size.


.RE
.B
\fBfitInside(This, Window) -> ok\fR
\fB                   when This :: wxSizer(), Window :: wxWindow:wxWindow().\fR

.br
.RS
.PP
Tell the sizer to resize the virtual size of the \fIwindow\fR to match the sizer's minimal size.

.PP
This will not alter the on screen size of the window, but may cause the addition/removal/alteration of scrollbars required to view the virtual area in windows which manage it.

.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxScrolledWindow:setScrollbars/6\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIsetVirtualSizeHints/2\fR

.RE


.RE
.B
\fBgetChildren(This) -> [wxSizerItem:wxSizerItem()]\fR
\fB                     when This :: wxSizer().\fR

.br
.RS

.RE
.B
\fBgetItem(This, Window) -> wxSizerItem:wxSizerItem()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Window :: wxWindow:wxWindow() | wxSizer:wxSizer();\fR
\fB             (This, Index) -> wxSizerItem:wxSizerItem()\fR
\fB                 when This :: wxSizer(), Index :: integer().\fR

.br
.RS
.PP
Finds \fIwxSizerItem\fR which is located in the sizer at position \fIindex\fR.

.PP
Use parameter \fIrecursive\fR to search in subsizers too. Returns pointer to item or NULL.


.RE
.B
\fBgetItem(This, Window, [Option]) -> wxSizerItem:wxSizerItem()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                     Option :: {recursive, boolean()}.\fR

.br
.RS
.PP
Finds \fIwxSizerItem\fR which holds the given \fIwindow\fR.

.PP
Use parameter \fIrecursive\fR to search in subsizers too. Returns pointer to item or NULL.


.RE
.B
\fBgetMinSize(This) -> {W :: integer(), H :: integer()}\fR
\fB                    when This :: wxSizer().\fR

.br
.RS
.PP
Returns the minimal size of the sizer.

.PP
This is either the combined minimal size of all the children and their borders or the minimal size set by \fIsetMinSize/3\fR, depending on which is bigger. Note that the returned value is client size, not window size. In particular, if you use the value to set toplevel window's minimal or actual size, use \fIwxWindow::SetMinClientSize()\fR (not implemented in wx) or \fIwxWindow:setClientSize/3\fR, not \fIwxWindow:setMinSize/2\fR or \fIwxWindow:setSize/6\fR.


.RE
.B
\fBgetPosition(This) -> {X :: integer(), Y :: integer()}\fR
\fB                     when This :: wxSizer().\fR

.br
.RS
.PP
Returns the current position of the sizer.


.RE
.B
\fBgetSize(This) -> {W :: integer(), H :: integer()}\fR
\fB                 when This :: wxSizer().\fR

.br
.RS
.PP
Returns the current size of the sizer.


.RE
.B
\fBhide(This, Window) -> boolean()\fR
\fB              when\fR
\fB                  This :: wxSizer(),\fR
\fB                  Window :: wxWindow:wxWindow() | wxSizer:wxSizer();\fR
\fB          (This, Index) -> boolean()\fR
\fB              when This :: wxSizer(), Index :: integer().\fR

.br
.RS
.PP
Hides the item at position \fIindex\fR.

.PP
To make a sizer item disappear, use \fIhide/3\fR followed by \fIlayout/1\fR.

.PP
Use parameter \fIrecursive\fR to hide elements found in subsizers. Returns true if the child item was found, false otherwise.

.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIisShown/2\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIshow/3\fR

.RE


.RE
.B
\fBhide(This, Window, [Option]) -> boolean()\fR
\fB              when\fR
\fB                  This :: wxSizer(),\fR
\fB                  Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                  Option :: {recursive, boolean()}.\fR

.br
.RS
.PP
Hides the child \fIwindow\fR.

.PP
To make a sizer item disappear, use \fIhide/3\fR followed by \fIlayout/1\fR.

.PP
Use parameter \fIrecursive\fR to hide elements found in subsizers. Returns true if the child item was found, false otherwise.

.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIisShown/2\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIshow/3\fR

.RE


.RE
.B
\fBinsert(This, Index, Item) -> wxSizerItem:wxSizerItem()\fR
\fB                when\fR
\fB                    This :: wxSizer(),\fR
\fB                    Index :: integer(),\fR
\fB                    Item :: wxSizerItem:wxSizerItem().\fR

.br
.RS

.RE
.B
\fBinsert(This, Index, Width, Height) -> wxSizerItem:wxSizerItem()\fR
\fB                when\fR
\fB                    This :: wxSizer(),\fR
\fB                    Index :: integer(),\fR
\fB                    Width :: integer(),\fR
\fB                    Height :: integer();\fR
\fB            (This, Index, Window, Flags) -> wxSizerItem:wxSizerItem()\fR
\fB                when\fR
\fB                    This :: wxSizer(),\fR
\fB                    Index :: integer(),\fR
\fB                    Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                    Flags :: wxSizerFlags:wxSizerFlags();\fR
\fB            (This, Index, Window, [Option]) -> wxSizerItem:wxSizerItem()\fR
\fB                when\fR
\fB                    This :: wxSizer(),\fR
\fB                    Index :: integer(),\fR
\fB                    Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                    Option ::\fR
\fB                        {proportion, integer()} |\fR
\fB                        {flag, integer()} |\fR
\fB                        {border, integer()} |\fR
\fB                        {userData, wx:wx_object()}.\fR

.br
.RS
.PP
Insert a child into the sizer before any existing item at \fIindex\fR.

.PP
See \fIadd/4\fR for the meaning of the other parameters.


.RE
.B
\fBinsert(This, Index, Width, Height, [Option]) ->\fR
\fB                wxSizerItem:wxSizerItem()\fR
\fB                when\fR
\fB                    This :: wxSizer(),\fR
\fB                    Index :: integer(),\fR
\fB                    Width :: integer(),\fR
\fB                    Height :: integer(),\fR
\fB                    Option ::\fR
\fB                        {proportion, integer()} |\fR
\fB                        {flag, integer()} |\fR
\fB                        {border, integer()} |\fR
\fB                        {userData, wx:wx_object()};\fR
\fB            (This, Index, Width, Height, Flags) ->\fR
\fB                wxSizerItem:wxSizerItem()\fR
\fB                when\fR
\fB                    This :: wxSizer(),\fR
\fB                    Index :: integer(),\fR
\fB                    Width :: integer(),\fR
\fB                    Height :: integer(),\fR
\fB                    Flags :: wxSizerFlags:wxSizerFlags().\fR

.br
.RS
.PP
Insert a child into the sizer before any existing item at \fIindex\fR.

.PP
See \fIadd/4\fR for the meaning of the other parameters.


.RE
.B
\fBinsertSpacer(This, Index, Size) -> wxSizerItem:wxSizerItem()\fR
\fB                      when\fR
\fB                          This :: wxSizer(),\fR
\fB                          Index :: integer(),\fR
\fB                          Size :: integer().\fR

.br
.RS
.PP
Inserts non-stretchable space to the sizer.

.PP
More readable way of calling wxSizer::Insert(index, size, size).


.RE
.B
\fBinsertStretchSpacer(This, Index, [Option]) ->\fR
\fB                             wxSizerItem:wxSizerItem()\fR
\fB                             when\fR
\fB                                 This :: wxSizer(),\fR
\fB                                 Index :: integer(),\fR
\fB                                 Option :: {prop, integer()}.\fR

.br
.RS
.PP
Inserts stretchable space to the sizer.

.PP
More readable way of calling wxSizer::Insert(0, 0, prop).


.RE
.B
\fBisShown(This, Window) -> boolean()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Window :: wxWindow:wxWindow() | wxSizer:wxSizer();\fR
\fB             (This, Index) -> boolean()\fR
\fB                 when This :: wxSizer(), Index :: integer().\fR

.br
.RS
.PP
Returns true if the item at \fIindex\fR is shown.

.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIhide/3\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIshow/3\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIwxSizerItem:isShown/1\fR

.RE


.RE
.B
\fBlayout(This) -> ok when This :: wxSizer().\fR

.br
.RS
.PP
Call this to force layout of the children anew, e.g. after having added a child to or removed a child (window, other sizer or space) from the sizer while keeping the current dimension.


.RE
.B
\fBprepend(This, Item) -> wxSizerItem:wxSizerItem()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Item :: wxSizerItem:wxSizerItem().\fR

.br
.RS

.RE
.B
\fBprepend(This, Width, Height) -> wxSizerItem:wxSizerItem()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Width :: integer(),\fR
\fB                     Height :: integer();\fR
\fB             (This, Window, Flags) -> wxSizerItem:wxSizerItem()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                     Flags :: wxSizerFlags:wxSizerFlags();\fR
\fB             (This, Window, [Option]) -> wxSizerItem:wxSizerItem()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                     Option ::\fR
\fB                         {proportion, integer()} |\fR
\fB                         {flag, integer()} |\fR
\fB                         {border, integer()} |\fR
\fB                         {userData, wx:wx_object()}.\fR

.br
.RS
.PP
Same as \fIadd/4\fR, but prepends the items to the beginning of the list of items (windows, subsizers or spaces) owned by this sizer.


.RE
.B
\fBprepend(This, Width, Height, [Option]) ->\fR
\fB                 wxSizerItem:wxSizerItem()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Width :: integer(),\fR
\fB                     Height :: integer(),\fR
\fB                     Option ::\fR
\fB                         {proportion, integer()} |\fR
\fB                         {flag, integer()} |\fR
\fB                         {border, integer()} |\fR
\fB                         {userData, wx:wx_object()};\fR
\fB             (This, Width, Height, Flags) -> wxSizerItem:wxSizerItem()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Width :: integer(),\fR
\fB                     Height :: integer(),\fR
\fB                     Flags :: wxSizerFlags:wxSizerFlags().\fR

.br
.RS
.PP
Same as \fIadd/4\fR, but prepends the items to the beginning of the list of items (windows, subsizers or spaces) owned by this sizer.


.RE
.B
\fBprependSpacer(This, Size) -> wxSizerItem:wxSizerItem()\fR
\fB                       when This :: wxSizer(), Size :: integer().\fR

.br
.RS
.PP
Prepends non-stretchable space to the sizer.

.PP
More readable way of calling wxSizer::Prepend(size, size, 0).


.RE
.B
\fBprependStretchSpacer(This, [Option]) -> wxSizerItem:wxSizerItem()\fR
\fB                              when\fR
\fB                                  This :: wxSizer(),\fR
\fB                                  Option :: {prop, integer()}.\fR

.br
.RS
.PP
Prepends stretchable space to the sizer.

.PP
More readable way of calling wxSizer::Prepend(0, 0, prop).


.RE
.B
\fBrecalcSizes(This) -> ok when This :: wxSizer().\fR

.br
.RS
.PP
Equivalent to: \fIlayout/1\fR


.RE
.B
\fBremove(This, Index) -> boolean()\fR
\fB                when This :: wxSizer(), Index :: integer();\fR
\fB            (This, Sizer) -> boolean()\fR
\fB                when This :: wxSizer(), Sizer :: wxSizer().\fR

.br
.RS
.PP
Removes a sizer child from the sizer and destroys it.

.PP
Note: This method does not cause any layout or resizing to take place, call \fIlayout/1\fR to update the layout "on screen" after removing a child from the sizer.

.PP
Return: true if the child item was found and removed, false otherwise.


.RE
.B
\fBreplace(This, Oldwin, Newwin) -> boolean()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Oldwin :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                     Newwin :: wxWindow:wxWindow() | wxSizer:wxSizer();\fR
\fB             (This, Index, Newitem) -> boolean()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Index :: integer(),\fR
\fB                     Newitem :: wxSizerItem:wxSizerItem().\fR

.br
.RS
.PP
Detaches the given item at position \fIindex\fR from the sizer and replaces it with the given \fIwxSizerItem\fR \fInewitem\fR.

.PP
The detached child is deleted \fIonly\fR if it is a sizer or a spacer (but not if it is a \fIwxWindow\fR because windows are owned by their parent window, not the sizer).

.PP
This method does not cause any layout or resizing to take place, call \fIlayout/1\fR to update the layout "on screen" after replacing a child from the sizer.

.PP
Returns true if the child item was found and removed, false otherwise.


.RE
.B
\fBreplace(This, Oldwin, Newwin, [Option]) -> boolean()\fR
\fB                 when\fR
\fB                     This :: wxSizer(),\fR
\fB                     Oldwin :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                     Newwin :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                     Option :: {recursive, boolean()}.\fR

.br
.RS
.PP
Detaches the given \fIoldwin\fR from the sizer and replaces it with the given \fInewwin\fR.

.PP
The detached child window is \fInot\fR deleted (because windows are owned by their parent window, not the sizer).

.PP
Use parameter \fIrecursive\fR to search the given element recursively in subsizers.

.PP
This method does not cause any layout or resizing to take place, call \fIlayout/1\fR to update the layout "on screen" after replacing a child from the sizer.

.PP
Returns true if the child item was found and removed, false otherwise.


.RE
.B
\fBsetDimension(This, Pos, Size) -> ok\fR
\fB                      when\fR
\fB                          This :: wxSizer(),\fR
\fB                          Pos :: {X :: integer(), Y :: integer()},\fR
\fB                          Size :: {W :: integer(), H :: integer()}.\fR

.br
.RS
.PP
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.


.RE
.B
\fBsetDimension(This, X, Y, Width, Height) -> ok\fR
\fB                      when\fR
\fB                          This :: wxSizer(),\fR
\fB                          X :: integer(),\fR
\fB                          Y :: integer(),\fR
\fB                          Width :: integer(),\fR
\fB                          Height :: integer().\fR

.br
.RS
.PP
Call this to force the sizer to take the given dimension and thus force the items owned by the sizer to resize themselves according to the rules defined by the parameter in the \fIadd/4\fR and \fIprepend/4\fR methods.


.RE
.B
\fBsetItemMinSize(This, Window, Size) -> boolean()\fR
\fB                        when\fR
\fB                            This :: wxSizer(),\fR
\fB                            Window ::\fR
\fB                                wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                            Size :: {W :: integer(), H :: integer()};\fR
\fB                    (This, Index, Size) -> boolean()\fR
\fB                        when\fR
\fB                            This :: wxSizer(),\fR
\fB                            Index :: integer(),\fR
\fB                            Size :: {W :: integer(), H :: integer()}.\fR

.br
.RS

.RE
.B
\fBsetItemMinSize(This, Window, Width, Height) -> boolean()\fR
\fB                        when\fR
\fB                            This :: wxSizer(),\fR
\fB                            Window ::\fR
\fB                                wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                            Width :: integer(),\fR
\fB                            Height :: integer();\fR
\fB                    (This, Index, Width, Height) -> boolean()\fR
\fB                        when\fR
\fB                            This :: wxSizer(),\fR
\fB                            Index :: integer(),\fR
\fB                            Width :: integer(),\fR
\fB                            Height :: integer().\fR

.br
.RS

.RE
.B
\fBsetMinSize(This, Size) -> ok\fR
\fB                    when\fR
\fB                        This :: wxSizer(),\fR
\fB                        Size :: {W :: integer(), H :: integer()}.\fR

.br
.RS
.PP
Call this to give the sizer a minimal size.

.PP
Normally, the sizer will calculate its minimal size based purely on how much space its children need. After calling this method \fIgetMinSize/1\fR will return either the minimal size as requested by its children or the minimal size set here, depending on which is bigger.


.RE
.B
\fBsetMinSize(This, Width, Height) -> ok\fR
\fB                    when\fR
\fB                        This :: wxSizer(),\fR
\fB                        Width :: integer(),\fR
\fB                        Height :: integer().\fR

.br
.RS
.PP
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.


.RE
.B
\fBsetSizeHints(This, Window) -> ok\fR
\fB                      when\fR
\fB                          This :: wxSizer(),\fR
\fB                          Window :: wxWindow:wxWindow().\fR

.br
.RS
.PP
This method first calls \fIfit/2\fR and then \fIsetSizeHints/2\fR on the \fIwindow\fR passed to it.

.PP
This only makes sense when \fIwindow\fR is actually a \fIwxTopLevelWindow\fR such as a \fIwxFrame\fR or a \fIwxDialog\fR, since SetSizeHints only has any effect in these classes. It does nothing in normal windows or controls.

.PP
This method is implicitly used by \fIwxWindow:setSizerAndFit/3\fR which is commonly invoked in the constructor of a toplevel window itself (see the sample in the description of \fIwxBoxSizer\fR) if the toplevel window is resizable.


.RE
.B
\fBsetVirtualSizeHints(This, Window) -> ok\fR
\fB                             when\fR
\fB                                 This :: wxSizer(),\fR
\fB                                 Window :: wxWindow:wxWindow().\fR

.br
.RS
.PP
Equivalent to: \fIfitInside/2\fR


.RE
.B
\fBshow(This, Window) -> boolean()\fR
\fB              when\fR
\fB                  This :: wxSizer(),\fR
\fB                  Window :: wxWindow:wxWindow() | wxSizer:wxSizer();\fR
\fB          (This, Index) -> boolean()\fR
\fB              when This :: wxSizer(), Index :: integer();\fR
\fB          (This, Show) -> ok when This :: wxSizer(), Show :: boolean().\fR

.br
.RS

.RE
.B
\fBshow(This, Window, [Option]) -> boolean()\fR
\fB              when\fR
\fB                  This :: wxSizer(),\fR
\fB                  Window :: wxWindow:wxWindow() | wxSizer:wxSizer(),\fR
\fB                  Option :: {show, boolean()} | {recursive, boolean()};\fR
\fB          (This, Index, [Option]) -> boolean()\fR
\fB              when\fR
\fB                  This :: wxSizer(),\fR
\fB                  Index :: integer(),\fR
\fB                  Option :: {show, boolean()}.\fR

.br
.RS
.PP
Shows the item at \fIindex\fR.

.PP
To make a sizer item disappear or reappear, use \fIshow/3\fR followed by \fIlayout/1\fR.

.PP
Returns true if the child item was found, false otherwise.

.PP
See:


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIhide/3\fR

.RE


.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}.PP
\fIisShown/2\fR

.RE


.RE
.B
\fBshowItems(This, Show) -> ok\fR
\fB                   when This :: wxSizer(), Show :: boolean().\fR

.br
.RS
.PP
Show or hide all items managed by the sizer.


.RE
